<?php // DO NOT EDIT THIS FILE BY ANY MEANS!

use Zenith\Setting\Setting;
return Cache::rememberForever('zenith', function() {
	$settings = array();
	foreach (Setting::all() as $setting) {
		$settings[$setting->key] = $setting->value;
	}
	return $settings;
});
